### ISSUE TITLE
Visual selection not visible.

### ISSUE THREAD

**Issue by natano** [fxn/vim-monochrome#1]
Visual selections and search highlights (set hlsearch) are not visible for me (TERM=xterm).

**Comment by natano** [comment]
Fwiw, 'hi Visual cterm=reverse' and 'hi Search cterm=reverse' fixes the issue for me.

**Comment by fxn** [comment]
Hey, I am no longer using Vim... if you try it and it works I'd merge a PR.

**Comment by fxn** [comment]
This seems to be working now.
