### ISSUE TITLE
Increase the visual contrast between whitespace and - / >

### ISSUE THREAD

**Issue by bradenbest** [fxn/vim-monochrome#7]
One of the things that bothers me about this colorscheme is that with `:set list` active, it's extremely difficult to tell whitespace apart from the characters they use to represent it. I'm talking specifically about

    >  used to represent a tab (^I)
    -  used to represent a trailing space.

The whitespace characters are very slightly whiter, but, I mean, look at it:

![image](https://gist.githubusercontent.com/bradenbest/c5bd2fc0d4e770486aff8daf94b7b0ed/raw/1d4bae1833b1bf00e7d7c00a5510762c2a049015/needs-more-contrast.png)

I don't care how much of a purist you are, this is very hard to distinguish and needs more contrast. Maybe make them grey like the `:set nu` numbers.

**Comment by fxn** [comment]
That's an overlook (I don't use that setting normally).

Your proposal seems good, would you mind sending a patch?

**Comment by bradenbest** [comment]
*Well*, I did find out how to change it. It's [`SpecialKey`](https://stackoverflow.com/a/24233486/1175714), and found that `sblue` was the easiest on the eyes while also being obvious enough. I don't know what else `SpecialKey` affects, though.

**Comment by bradenbest** [comment]
#8
