### ISSUE TITLE
Missing style for SignColumn (used by debuggers/linters)

### ISSUE THREAD

**Issue by saalaa** [fxn/vim-monochrome#9]
As shown in the attached screenshot, *monochrome* currently looks aggressive:

![bad](https://user-images.githubusercontent.com/331635/46081166-22573680-c19c-11e8-93d8-98de73c63f94.png)

I propose that the following style is added:

    call s:hi('SignColumn')

So that it looks like this:

![good](https://user-images.githubusercontent.com/331635/46081243-55012f00-c19c-11e8-9a60-2bbb6743945f.png)

**Comment by fxn** [comment]
Indeed, I don't use debuggers and overlooked that one. Your suggestion looks great and the patch is up.

Thank you!

**Comment by saalaa** [comment]
Wonderful, thanks a ton!
